### ISSUE TITLE
我还是直接发错误吧！

### ISSUE THREAD

**Issue by user1121114685** [deadblue/elevengo#26]
`panic: runtime error: slice bounds out of range [:34518] with capacity 3520

goroutine 1 [running]:
github.com/deadblue/elevengo/internal/crypto/ec115.(*Cipher).Decode(0xc00006c0f0, {0xc00023f000, 0xdcc, 0x1000})
        G:/elevengo-master/elevengo-master/internal/crypto/ec115/api.go:81 +0x1d6
github.com/deadblue/elevengo/internal/web.(*Client).CallSecretJsonApi(0xc000068300, {0xcc23d6, 0x27}, 0x5?, {0xd360c0, 0xc00000a4e0}, {0xd33cc0?, 0xc0002c8fc0}, 0xc00021da30?)
        G:/elevengo-master/elevengo-master/internal/web/api.go:91 +0x3c6
github.com/deadblue/elevengo.(*Agent).uploadInitInternal(0xc00013c070, 0xc00021dc70, 0x0)
        G:/elevengo-master/elevengo-master/upload.go:74 +0x772
github.com/deadblue/elevengo.(*Agent).Import(0xc00013c070, {0xc0001e9698, 0x13}, 0xc00033b880)
        G:/elevengo-master/elevengo-master/import.go:54 +0x1b5
115push/receiver.importFileForDir({0xc0001e9698, 0x13}, {0xc0002a4048, 0x15}, 0xc?)
        G:/GitHub/115push/receiver/receiver.go:70 +0xdd
115push/receiver.Import({0xc0002a4018, 0x13}, {0xc0002a4048, 0x15}, {0xc0002a4060, 0x13})
        G:/GitHub/115push/receiver/receiver.go:40 +0x218
main.main()
        G:/GitHub/115push/main.go:45 +0x50e`

这个就是我提议的那个软件，还在测试。大佬麻烦看看有什么地方不对。我感觉是二次长度传入的问题

**Comment by deadblue** [comment]
出错是 internal/crypto/ec115/api.go 第81行，错误原因是切片越界，应该是 `plaintext[2:srcSize+2]` 这里。

看来 EC Decode 里面还有一些逻辑要处理。

**Comment by user1121114685** [comment]
这种怕是不好复现把！我也是十几次遇到1次 如果要调试IDE都废了

**Comment by xqmaster** [comment]
srcSize := binary.LittleEndian.Uint16(plaintext[0:2])
如果不是加密数据，srcSize这样计算肯定是不对的

**Comment by deadblue** [comment]
> 出现的原因是因为流控，返回的数据不是加密的数据，是一个网页数据

原来是这样么，正好加密数据的最后4字节是校验位，我用它做个校验好了，如果校验不通过，那么可能返回了错误数据。

**Comment by user1121114685** [comment]
谢谢各位大佬，这玩意出现就让他等几分钟吧！

**Comment by xqmaster** [comment]
> 谢谢各位大佬，这玩意出现就让他等几分钟吧！

只要不是连续多次无间隔时间的api请求，都不会出现流控，就算出现了，也不用等几分钟，等几秒就正常了

**Comment by user1121114685** [comment]
确实没做控制，理论模型上因为http延迟应该达不到上限，但是测试过程中自己给自己弄就很容易达到。

**Comment by deadblue** [comment]
处理校验位的代码合到了 master 分支，暂时先不打 tag 了，还有点别的改动在搞。

如果着急可以先拉 master 分支的最新代码用。

**Comment by user1121114685** [comment]
感谢大佬

**Comment by user1121114685** [comment]
runtime error: slice bounds out of range:[:-12]
暂时没有找到复现，等我找到复现的再来补充

**Comment by deadblue** [comment]
> runtime error: slice bounds out of range:[:-12] 暂时没有找到复现，等我找到复现的再来补充

看错误应该是响应数据为空导致的，估计又是服务端挂了，我在这个地方加个校验，避免panic导致程序崩溃。
